spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem://localhost/~/playground
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create # 실제 환경에서 절대 금지
    defer-datasource-initialization: true # Spring boot 2.5 이상
    properties:
      hibernate:
        format_sql: true
