spring:
  jpa:
    open-in-view: false
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true

    database-platform: h2
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true

  datasource:
    hikari:
      jdbc-url: jdbc:h2:tcp://localhost:9099/mem:testdb
      driver-class-name: org.h2.Driver
      username: sa
      password:

  sql:
    init:
      mode: always
      data-locations: classpath:db/h2/data.sql
