### document 단건 조회
GET http://localhost:8080/api/documents/1

### document outbox 조회
GET http://localhost:8080/api/documents/outbox?drafterId=1

### document category 조회
GET http://localhost:8080/api/documents/categories

### document create
POST http://localhost:8080/api/documents
Content-Type: application/json

{
  "title": "교육비 결재 요청",
  "category": "EDUCATION",
  "contents": "사외교육비 결재 요청드립니다.",
  "drafterId": 1,
  "approverIds": [
    1,
    2
  ]
}
